services:
  web:
    build: .
    container_name: "Django"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: "Db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    container_name: "Adminer"
    ports:
      - "8080:8080"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: 'Redis'
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: 'Celery'
    command: celery -A Veyra worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    container_name: 'Celery Beat'
    env_file:
      - .env
    command: celery -A Veyra beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  static:
  media:
  postgres_data:
  redis_data: