# Generated by Django 6.0.6 on 2026-09-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_created_at_productvariant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='main_image',
            field=models.ImageField(default='', upload_to='variants/'),
        ),
    ]
