# Generated by Django 6.0.6 on 2026-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariant_unique_product_color_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_code',
            field=models.SlugField(blank=True, max_length=80),
        ),
    ]
